networks:
  back-tier:
    internal: true  
  front-tier:
    internal: false 

services:
  v1:
    build: ./vote
    ports: 
    - "5001:5000"
    depends_on:
      - redis
      - db
    networks:
      - front-tier
      - back-tier
    

 
  v2:
    build: ./vote
    ports: 
    - "5002:5000"
    depends_on:
      - redis
      - db
    networks:
      - front-tier
      - back-tier

  loadbalancer:
    build: ./nginx
    ports:
      - 8000:80
    networks:
      - front-tier
    depends_on:
      - v1
      - v2
  
  redis:
    image: redis:alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - back-tier
    # volumes: 
    #   - ./healthcheks/:/healthcheks/
    # command: ./healthcheks/redis.sh
  db:
    image: postgres:15-alpine
    networks:
      - back-tier
    environment:
      POSTGRES_USER: myuser 
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes: 
      - db-data:/var/lib/postgresql/data/
    # command: ./healthcheks/postgres.sh


  # seed:
  #   build: ./seed-data
  #   depends_on:
  #     - nginx

  worker:
    build: ./worker
    depends_on:
      - redis
      - db
    networks:
      - back-tier
  result:
    build: ./result
    depends_on: 
      - v1
      - v2
      - db
    networks:
      - back-tier
      - front-tier
volumes: 
  db-data:
    name: my-db-data