services:
  v1:
    build: ./vote
    ports: 
    - "5001:5000"
    depends_on:
      - redis
 
  v2:
    build: ./vote
    ports: 
    - "5002:5000"
    depends_on:
      - redis

  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - redis


  redis:
    image: redis:alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes: 
    - ./healthchecks/:/healthchecks/  # This ensures scripts exist inside the container
    

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes: 
      - db-data:/var/lib/postgresql/data/
      # - ./healthchecks/:/healthchecks/
    # command: ["/healthchecks/postgres.sh"]
    ports:
    - "5432:5432"
  
  # seed:
  #   build: ./seed-data
  #   depends_on:
  #     - nginx

  worker:
    build: ./worker
    depends_on:
      - redis
      - db

volumes: 
  db-data:
    