apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis  # Matches the Deployment labels
  ports:
    - protocol: TCP
      port: 6379  # External port
      targetPort: 6379  # Port inside the container
  type: LoadBalancer  # Exposes the service outside the cluster