apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: europe-west4-docker.pkg.dev/spry-tree-453513-c0/voting-image/result
        ports:
        - containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: result-service
spec:
  selector:
    app: result  # Matches the Deployment labels
  ports:
    - protocol: TCP
      port: 4000  # External port
      targetPort: 4000  # Port inside the container
  type: LoadBalancer  # Exposes the service outside the cluster