apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: europe-west4-docker.pkg.dev/spry-tree-453513-c0/voting-image/v1
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: vote-service
spec:
  selector:
    app: vote  # Matches the Deployment labels
  ports:
    - protocol: TCP
      port: 5000  # External port
      targetPort: 5000  # Port inside the container
  type: LoadBalancer  # Exposes the service outside the cluster